# Generated by Django 5.0 on 2024-01-19 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminChannels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.BigIntegerField(unique=True)),
                ("title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user_id", models.BigIntegerField()),
                ("unique_id", models.TextField(default=uuid.uuid4, unique=True)),
                ("added_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("channel_id", models.BigIntegerField()),
                ("channel_message_id", models.BigIntegerField()),
                ("group_id", models.BigIntegerField(blank=True, null=True)),
                ("group_message_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "conversation_type",
                    models.TextField(
                        choices=[
                            ("NQ", "New Quote"),
                            ("RQ", "Response To Quote"),
                            ("NS", "New Sale"),
                            ("RS", "Response To Sale"),
                        ]
                    ),
                ),
                ("direct_forward", models.BooleanField(default=False)),
                ("is_accepted", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="BotAdmins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField(unique=True)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BrokerChannels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.BigIntegerField(unique=True)),
                ("title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.TextField(
                        choices=[
                            ("PC", "Private Channel"),
                            ("LC", "Log Channel"),
                            ("T", "Timeout"),
                        ],
                        unique=True,
                    ),
                ),
                ("value", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_order", models.IntegerField()),
                ("question_text", models.TextField()),
                ("regex_pattern", models.TextField(blank=True, null=True)),
                ("error_response", models.TextField(blank=True, null=True)),
                ("is_private_question", models.BooleanField(default=False)),
                (
                    "conversation_type",
                    models.TextField(
                        choices=[
                            ("NQ", "New Quote"),
                            ("RQ", "Response To Quote"),
                            ("NS", "New Sale"),
                            ("RS", "Response To Sale"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QnA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user_id", models.BigIntegerField()),
                ("response_text", models.TextField(default="")),
                ("unique_id", models.TextField(default=uuid.uuid4, unique=True)),
                ("question_order", models.IntegerField()),
                ("question_text", models.TextField()),
                ("regex_pattern", models.TextField(blank=True, null=True)),
                ("error_response", models.TextField(blank=True, null=True)),
                ("is_private_question", models.BooleanField()),
                (
                    "conversation_type",
                    models.TextField(
                        choices=[
                            ("NQ", "New Quote"),
                            ("RQ", "Response To Quote"),
                            ("NS", "New Sale"),
                            ("RS", "Response To Sale"),
                        ]
                    ),
                ),
                (
                    "linked_ad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.ads",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QnAForAds",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user_id", models.BigIntegerField()),
                ("response_text", models.TextField()),
                ("unique_id", models.TextField(default=uuid.uuid4, unique=True)),
                ("question_order", models.IntegerField()),
                ("question_text", models.TextField()),
                ("regex_pattern", models.TextField(blank=True, null=True)),
                ("error_response", models.TextField(blank=True, null=True)),
                ("is_private_question", models.BooleanField()),
                (
                    "conversation_type",
                    models.TextField(
                        choices=[
                            ("NQ", "New Quote"),
                            ("RQ", "Response To Quote"),
                            ("NS", "New Sale"),
                            ("RS", "Response To Sale"),
                        ]
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.ads"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Replies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user_id", models.BigIntegerField()),
                ("unique_id", models.TextField(default=uuid.uuid4, unique=True)),
                ("added_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "conversation_type",
                    models.TextField(
                        choices=[
                            ("NQ", "New Quote"),
                            ("RQ", "Response To Quote"),
                            ("NS", "New Sale"),
                            ("RS", "Response To Sale"),
                        ]
                    ),
                ),
                ("is_shared_with_author", models.BooleanField(default=False)),
                (
                    "linked_ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.ads"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QnAForReplies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_user_id", models.BigIntegerField()),
                ("response_text", models.TextField()),
                ("unique_id", models.TextField(default=uuid.uuid4, unique=True)),
                ("question_order", models.IntegerField()),
                ("question_text", models.TextField()),
                ("regex_pattern", models.TextField(blank=True, null=True)),
                ("error_response", models.TextField(blank=True, null=True)),
                ("is_private_question", models.BooleanField()),
                (
                    "conversation_type",
                    models.TextField(
                        choices=[
                            ("NQ", "New Quote"),
                            ("RQ", "Response To Quote"),
                            ("NS", "New Sale"),
                            ("RS", "Response To Sale"),
                        ]
                    ),
                ),
                (
                    "replies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="db.replies"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ads",
            name="accepted_offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="db.replies",
            ),
        ),
    ]
